/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mathquiz;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.net.Socket;
import java.net.SocketException;
import javax.swing.JOptionPane;
import java.util.Comparator;


public class MathQuizz_Student extends javax.swing.JFrame {

   static Socket socket;
static DataInputStream dataInputStream;
static DataOutputStream dataOutputStream;
static int correctAnswer;
static int studentAnswer;

    public MathQuizz_Student() {
        initComponents();
    }
public class Node<T extends Comparable <T>> implements Comparable<Node<T>>
{
    // data component
    public T data;
    // reference to the left child node (a memory address)
    public Node<T> leftChild;
    // reference to the right child node (a memory address)
    public Node<T> rightChild;

    // constructor method for Node()
    // initialise data
    // set right and left child nodes to null
    public Node(T data)
    {
        // when initialised, this default constructor sets up the input data
        // to get assigned to the new object's data
        // the references for the left and right child nodes are made null
        // as none exist at this point
        this.data = data;
        rightChild = null;
        leftChild = null;
    }
    
    @Override
    public String toString()
    {
        return data.toString();
    }

    // Search() method to find a particular data value
    // as this is a generic data type <T>, this uses a compareTo() method
    public boolean search(Node<T> node, T data)
    {
        // if node is null, then this is the root node
        if (node == null)
        {
            return false;
        }
        else
        {
            // existing node --- check if data is > node.data
            if (node.data.compareTo(data) > 0)
            {
                    return search(node.rightChild, data);
            }
            // existing data --- check if data is < node.data
            else if (node.data.compareTo(data) < 0)
            {
                return search(node.leftChild, data);
            }
            // if existing data is the same as node.data
            else
            {
                return true;
            }
        }
    }
    
    // implement compareTo() method
    public int compareTo (Node <T> otherNode)
    {
        // use Comparable interface built-in compareTo() method
        // returns  0 if this.data == otherNode.data
        // returns -1 if this.data < otherNode.data
        // returns  1 if this.data > otherNode.data
        return this.data.compareTo(otherNode.data);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Question_JTextField = new javax.swing.JTextField();
        Answer_JTextField = new javax.swing.JTextField();
        Submit_JButton = new javax.swing.JButton();
        Exit_JButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student");

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Student");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 255));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter your answer and click Submit");

        jLabel3.setText("Question:");

        jLabel4.setText("Your Answer");

        Submit_JButton.setText("Submit");
        Submit_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_JButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Answer_JTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(Question_JTextField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Submit_JButton)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Question_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Answer_JTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(Submit_JButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        Exit_JButton.setText("Exit");
        Exit_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_JButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Exit_JButton)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(48, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Exit_JButton)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Submit_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_JButtonActionPerformed
        // TODO add your handling code here:
        try
      {
        String messageOut = "n";
        
         // get answer from student
         try
         {
         studentAnswer = Integer.parseInt (Answer_JTextField.getText());
         }
          catch (Exception e)
        {
            String exceptionStr = "Error: need to provide a number for your answer  " + e.getMessage();
            JOptionPane.showMessageDialog(null, exceptionStr,
           "STUDENT SEND ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // compare student's answer with correct 
        if (studentAnswer == correctAnswer)
        {
            messageOut = "y";
            JOptionPane.showMessageDialog(null, "CORRECT!","Answer is correct", JOptionPane.INFORMATION_MESSAGE);  
        }
        
        else
        {
            JOptionPane.showMessageDialog(null, "INCORRECT!","Answer is incorrect", JOptionPane.INFORMATION_MESSAGE);  
        }
          dataOutputStream.writeUTF(messageOut);
         // display message sent from client to server


        // clear send text field
        Answer_JTextField.setText("");
        Question_JTextField.setText("");
        }
        catch (Exception e)
        {
            String exceptionStr = "Student Send Error: " + e.getMessage();
            JOptionPane.showMessageDialog(null, exceptionStr,
           "STUDENT SEND ERROR", JOptionPane.ERROR_MESSAGE);
          
 }
 

    }//GEN-LAST:event_Submit_JButtonActionPerformed

    private void Exit_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_JButtonActionPerformed
        setVisible(false);
            dispose();
                System.exit(0);
    }//GEN-LAST:event_Exit_JButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MathQuizz_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MathQuizz_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MathQuizz_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MathQuizz_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MathQuizz_Student().setVisible(true);
            }
        });
          try
        { 
            socket = new Socket("127.0.0.1", 1201);
            dataInputStream = new
            DataInputStream(socket.getInputStream());
            dataOutputStream = new
            DataOutputStream(socket.getOutputStream());
            String messageIn = "";
            
        while(!messageIn.equals("exit")) {
            messageIn = dataInputStream.readUTF();
            Submit_JButton.setEnabled(true);
            String[] arrayMathQuestions = messageIn.split(" ");
            int number1 = Integer.parseInt(arrayMathQuestions[0]);
            String operator = arrayMathQuestions[1];
            int number2 = Integer.parseInt(arrayMathQuestions[2]);
            correctAnswer = Integer.parseInt(arrayMathQuestions[4]);
            Question_JTextField.setText(number1 + " " + operator + " " + number2 + " =");

          
}
    }   
    catch (SocketException se)
    {
        String exceptionStr = "Student Socket Error: " + se.getMessage();
        JOptionPane.showMessageDialog(null, exceptionStr, "STUDENT ERROR", JOptionPane.ERROR_MESSAGE);
    }
    catch(Exception e)
    {
        System.out.println(e);
        String exceptionStr = "Student Error: " + e.getMessage();
        JOptionPane.showMessageDialog(null, exceptionStr, "STUDENT ERROR", JOptionPane.ERROR_MESSAGE);
}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Answer_JTextField;
    private javax.swing.JButton Exit_JButton;
    private static javax.swing.JTextField Question_JTextField;
    private static javax.swing.JButton Submit_JButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
